# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  myfind_config = debug
endif
ifeq ($(config),release)
  myfind_config = release
endif

PROJECTS := myfind

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

myfind:
ifneq (,$(myfind_config))
	@echo "==== Building myfind ($(myfind_config)) ===="
	@${MAKE} --no-print-directory -C myfind -f Makefile config=$(myfind_config)
endif

clean:
	@${MAKE} --no-print-directory -C myfind -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   myfind"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"